export const country: any = {
	ar: 'Argentina',
	br: 'Brasil',
	by: 'Belarus',
	cn: 'China',
	de: 'Germany',
	es: 'Spain',
	fi: 'Finland',
	fr: 'France',
	gb: 'UK',
	gr: 'Greece',
	it: 'Italy',
	jp: 'Japan',
	kr: 'South Korea',
	nl: 'Netherlands',
	ru: 'Russia',
	us: 'USA',
}

// export const country = {

// // Europe

// 	al: 'Albania',
// 	at: 'Austria',
// 	by: 'Belarus',
// 	be: 'Belgium',
// 	bg: 'Bulgaria',
// 	hr: 'Croatia',
// 	cy: 'Cyprus',
// 	cz: 'Czech Republic',
// 	dk: 'Denmark',
// 	ee: 'Estonia',
// 	fi: 'Finland',
// 	fr: 'France',
// 	de: 'Germany',
// 	gr: 'Greece',
// 	hu: 'Hungary',
// 	is: 'Iceland',
// 	ie: 'Ireland',
// 	it: 'Italy',
// 	lv: 'Latvia',
// 	lt: 'Lithuania',
// 	lu: 'Luxembourg',
// 	mk: 'Macedonia',
// 	mt: 'Malta',
// 	md: 'Moldova',
// 	nl: 'Netherlands',
// 	no: 'Norway',
// 	pl: 'Poland',
// 	pt: 'Portugal',
// 	ro: 'Romania',
// 	ru: 'Russia',
// 	sk: 'Slovakia',
// 	si: 'Slovenia',
// 	es: 'Spain',
// 	se: 'Sweden',
// 	ch: 'Switzerland',
// 	tr: 'Turkey',
// 	ua: 'Ukraine',
// 	gb: 'United Kingdom',

// // Americas

// 	ai: 'Anguilla',
// 	ag: 'Antigua and Barbuda',
// 	ar: 'Argentina',
// 	bs: 'Bahamas',
// 	bb: 'Barbados',
// 	bz: 'Belize',
// 	bm: 'Bermuda',
// 	bo: 'Bolivia',
// 	br: 'Brasil',
// 	ky: 'Cayman Islands',
// 	cl: 'Chile',
// 	co: 'Colombia',
// 	cr: 'Costa Rica',
// 	dm: 'Dominica',
// 	do: 'Dominican Republic',
// 	ec: 'Ecuador',
// 	sv: 'El Salvador',
// 	gd: 'Grenada',
// 	gt: 'Guatemala',
// 	gy: 'Guyana',
// 	hn: 'Honduras',
// 	jm: 'Jamaica',
// 	mx: 'Mexico',
// 	ms: 'Montserrat',
// 	ni: 'Nicaragua',
// 	pa: 'Panama',
// 	py: 'Paraguay',
// 	pe: 'Peru',
// 	lc: 'Saint Lucia',
// 	kn: 'Saint Kitts and Nevis',
// 	vc: 'Saint Vincent and Grenadines',
// 	sr: 'Suriname',
// 	tt: 'Trinidad and Tobago',
// 	tc: 'Turks and Caicos Islands',
// 	uy: 'Uruguay',
// 	ve: 'Venezuela',
// 	vg: 'British Virgin Islands',
// 	ca: 'Canada',
// 	us: 'USA',

// // Africa and Asia

// 	dz: 'Algeria',
// 	ao: 'Angola',
// 	am: 'Armenia',
// 	az: 'Azerbaijan',
// 	bh: 'Bahrain',
// 	bj: 'Benin',
// 	bw: 'Botswana',
// 	bf: 'Burkina Faso',
// 	cv: 'Cape Verde',
// 	td: 'Chad',
// 	cg: 'Congo',
// 	eg: 'Egypt',
// 	gm: 'Gambia',
// 	gh: 'Ghana',
// 	gw: 'Guinea-Bissau',
// 	in: 'India',
// 	il: 'Israel',
// 	jo: 'Jordan',
// 	ke: 'Kenya',
// 	kw: 'Kuwait',
// 	lb: 'Lebanon',
// 	lr: 'Liberia',
// 	mg: 'Madagascar',
// 	mw: 'Malawi',
// 	ml: 'Mali',
// 	mr: 'Mauritania',
// 	mu: 'Mauritius',
// 	mz: 'Mozambique',
// 	na: 'Namibia',
// 	ne: 'Niger',
// 	ng: 'Nigeria',
// 	om: 'Oman',
// 	qa: 'Qatar',
// 	sa: 'Saudi Arabia',
// 	sn: 'Senegal',
// 	sc: 'Seychelles',
// 	sl: 'Sierra Leone',
// 	za: 'South Africa',
// 	sz: 'Swaziland',
// 	st: 'Sao Tome and Principe',
// 	tz: 'Tanzania',
// 	tn: 'Tunisia',
// 	ug: 'Uganda',
// 	ae: 'United Arab Emirates',
// 	ye: 'Yemen',
// 	zw: 'Zimbabwe',

// // Central and Southeast Asia

// 	au: 'Australia',
// 	bt: 'Bhutan',
// 	bn: 'Brunei Darussalam',
// 	kh: 'Cambodia',
// 	cn: 'China',
// 	fj: 'Fiji',
// 	hk: 'Hong Kong',
// 	id: 'Indonesia',
// 	jp: 'Japan',
// 	kz: 'Kazakhstan',
// 	kr: 'South Korea',
// 	kg: 'Kyrgyzstan',
// 	la: 'Laos',
// 	mo: 'Macao',
// 	my: 'Malaysia',
// 	fm: 'Micronesia',
// 	mn: 'Mongolia',
// 	np: 'Nepal',
// 	nz: 'New Zealand',
// 	pk: 'Pakistan',
// 	pw: 'Palau',
// 	pg: 'Papua New Guinea',
// 	ph: 'Philippines',
// 	sg: 'Singapore',
// 	sb: 'Solomon Islands',
// 	lk: 'Sri Lanka',
// 	tw: 'Taiwan',
// 	tj: 'Tajikistan',
// 	th: 'Thailand',
// 	tm: 'Turkmenistan',
// 	uz: 'Uzbekistan',
// 	vn: 'Viet Nam',
// }
